# Main CI for the project.
# Releases all apps that are waiting on new versions as long as build & other steps succeed.
name: CI

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.0

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install pkg
        run: pnpm install -g pkg

      - name: Run pipeline
        run: pnpx turbo run clean build tar release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
