name: CI

on:
  push:
    branches:
      - master
      - beta
      - alpha

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Load next version into an environment variable
        run: |
          npx semantic-release -d | grep -oP 'Published release \K.*? ' >> .next-version
          echo "AARD_NEXT_VERSION=$(cat .next-version)" >> $GITHUB_ENV
          rm .next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: yarn build

      - name: Install and run pkg
        run: |
          npm install -g pkg
          pkg .

      - name: Bundle and create tarball
        run: |
          yarn bundle
          yarn tar

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
