# Main CI for the project.
# Releases all apps that are waiting on new versions as long as build & other steps succeed.
name: CI

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Install pkg
        run: npm install -g pkg

      - name: Build
        run: yarn build

      - name: Run pipeline
        run: npx turbo run build tar release
