name: Semantic Test

on:
  push:
    branches:
      - develop

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install deps
        run: yarn install

      - name: Load next version into an environment variable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release -d --branches develop
          npx semantic-release -d --branches develop | grep -oP 'Published release \K.*? ' >> .next-version
          echo "AARD_NEXT_VERSION=$(cat .next-version)" >> $GITHUB_ENV
          rm .next-version

      - name: Echo version
        run: |
          echo Version:
          echo $AARD_NEXT_VERSION
